# Generated by Django 4.1.13 on 2024-06-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('num_persons', models.IntegerField()),
                ('prize', models.CharField(blank=True, max_length=255)),
                ('arrived', models.BooleanField(default=False)),
            ],
        ),
    ]
