# Generated by Django 5.0.6 on 2024-07-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0003_stall_stallvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='email',
            field=models.EmailField(default='shobikunnariyath@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='qr_code',
            field=models.CharField(default='6f986337-2964-4dc2-859e-0e9859c35a97', max_length=100),
        ),
    ]
